Participants:
- DomainObjectId: approver
  StateIds: []
  ExcludedStateIds: []
  EventStates: []
- DomainObjectId: manager
  StateIds: []
  ExcludedStateIds: []
  EventStates: []
- DomainObjectId: application
  StateIds: []
  ExcludedStateIds: []
  EventStates:
  - EventId: application.recieved
  - StateId: application.in-queue
- DomainObjectId: account
  StateIds: []
  ExcludedStateIds: []
  EventStates: []
- DomainObjectId: card
  StateIds: []
  ExcludedStateIds: []
  EventStates: []
Rules: []
Key: recieve-application
Name: Recieve Application
